-- ===================================================================
-- DML - Inserção Clientes 
-- ===================================================================

INSERT INTO public.Cliente (NomeCliente, EmailCliente, Senha, Rua, Bairro, IDMunicipio) VALUES
('Helena Martins', 'helena.martins@email.com', 'senha123', 'Rua das Gaivotas, 101', 'Jardim Oceânico', 35),
('Miguel Pereira', 'miguel.pereira@email.com', 'senha123', 'Avenida das Américas, 202', 'Barra da Tijuca', 35),
('Alice Ferreira', 'alice.ferreira@email.com', 'senha123', 'Rua Visconde de Pirajá, 303', 'Ipanema', 35),
('Arthur Rodrigues', 'arthur.rodrigues@email.com', 'senha123', 'Travessa das Laranjeiras, 404', 'Laranjeiras', 35),
('Laura Almeida', 'laura.almeida@email.com', 'senha123', 'Rua do Catete, 505', 'Catete', 35),
('Heitor Lima', 'heitor.lima@email.com', 'senha123', 'Avenida Atlântica, 606', 'Copacabana', 35),
('Manuela Barbosa', 'manuela.barbosa@email.com', 'senha123', 'Rua Augusta, 707', 'Consolação', 48),
('Bernardo Gonçalves', 'bernardo.goncalves@email.com', 'senha123', 'Avenida Brigadeiro Faria Lima, 808', 'Jardim Paulistano', 48),
('Valentina Ribeiro', 'valentina.ribeiro@email.com', 'senha123', 'Rua Oscar Freire, 909', 'Jardins', 48),
('Davi Nogueira', 'davi.nogueira@email.com', 'senha123', 'Alameda Santos, 1010', 'Cerqueira César', 48),
('Sophia Mendes', 'sophia.mendes@email.com', 'senha123', 'Rua da Consolação, 1111', 'Consolação', 48),
('Theo Cavalcanti', 'theo.cavalcanti@email.com', 'senha123', 'Avenida Ipiranga, 1212', 'República', 48),
('Isabella Santos', 'isabella.santos@email.com', 'senha123', 'Praça da Sé, 1313', 'Sé', 48),
('Lorenzo Silva', 'lorenzo.silva@email.com', 'senha123', 'Rua 25 de Março, 1414', 'Sé', 48),
('Júlia Oliveira', 'julia.oliveira@email.com', 'senha123', 'Avenida Tiradentes, 1515', 'Luz', 48),
('Pedro Souza', 'pedro.souza@email.com', 'senha123', 'Rua Direita, 1616', 'Sé', 48),
('Luiza Costa', 'luiza.costa@email.com', 'senha123', 'Largo do Arouche, 1717', 'República', 48),
('Gabriel Pereira', 'gabriel.pereira@email.com', 'senha123', 'Avenida São João, 1818', 'Centro', 48),
('Maria Clara Rodrigues', 'mariaclara.rodrigues@email.com', 'senha123', 'Rua Sete de Setembro, 1919', 'Centro', 35),
('Lucas Ferreira', 'lucas.ferreira@email.com', 'senha123', 'Avenida Rio Branco, 2020', 'Centro', 35),
('Beatriz Almeida', 'beatriz.almeida@email.com', 'senha123', 'Rua do Ouvidor, 2121', 'Centro', 35),
('Matheus Lima', 'matheus.lima@email.com', 'senha123', 'Praça XV de Novembro, 2222', 'Centro', 35),
('Yasmin Barbosa', 'yasmin.barbosa@email.com', 'senha123', 'Avenida Presidente Vargas, 2323', 'Centro', 35),
('Nicolas Gonçalves', 'nicolas.goncalves@email.com', 'senha123', 'Rua Uruguaiana, 2424', 'Centro', 35),
('Mariana Ribeiro', 'mariana.ribeiro@email.com', 'senha123', 'Largo da Carioca, 2525', 'Centro', 35),
('Rafael Nogueira', 'rafael.nogueira@email.com', 'senha123', 'Rua da Alfândega, 2626', 'Centro', 35),
('Lívia Mendes', 'livia.mendes@email.com', 'senha123', 'Avenida Passos, 2727', 'Centro', 35),
('Guilherme Cavalcanti', 'guilherme.cavalcanti@email.com', 'senha123', 'Rua Sete de Abril, 2828', 'República', 48),
('Letícia Santos', 'leticia.santos@email.com', 'senha123', 'Praça da República, 2929', 'República', 48),
('Enzo Silva', 'enzo.silva@email.com', 'senha123', 'Rua Barão de Itapetininga, 3030', 'República', 48),
('Ana Júlia Oliveira', 'anajulia.oliveira@email.com', 'senha123', 'Avenida Vieira de Carvalho, 3131', 'República', 48),
('Bruno Souza', 'bruno.souza@email.com', 'senha123', 'Largo do Paissandu, 3232', 'República', 48),
('Melissa Costa', 'melissa.costa@email.com', 'senha123', 'Rua Dom José de Barros, 3333', 'República', 48),
('Emanuel Pereira', 'emanuel.pereira@email.com', 'senha123', 'Rua 24 de Maio, 3434', 'República', 48),
('Sarah Rodrigues', 'sarah.rodrigues@email.com', 'senha123', 'Avenida Cásper Líbero, 3535', 'Luz', 48),
('Cauã Almeida', 'caua.almeida@email.com', 'senha123', 'Rua Washington Luís, 3636', 'Luz', 48),
('Esther Lima', 'esther.lima@email.com', 'senha123', 'Praça da Luz, 3737', 'Luz', 48),
('Isaac Barbosa', 'isaac.barbosa@email.com', 'senha123', 'Rua Mauá, 3838', 'Luz', 48),
('Rebeca Gonçalves', 'rebeca.goncalves@email.com', 'senha123', 'Rua Santa Ifigênia, 3939', 'Santa Efigênia', 48),
('Daniel Ribeiro', 'daniel.ribeiro@email.com', 'senha123', 'Rua dos Timbiras, 4040', 'Santa Efigênia', 48),
('Elisa Nogueira', 'elisa.nogueira@email.com', 'senha123', 'Avenida Ipiranga, 4141', 'Santa Efigênia', 48),
('Calebe Mendes', 'calebe.mendes@email.com', 'senha123', 'Rua dos Gusmões, 4242', 'Santa Efigênia', 48),
('Antonella Cavalcanti', 'antonella.cavalcanti@email.com', 'senha123', 'Alameda Barão de Limeira, 4343', 'Santa Efigênia', 48),
('Rodrigo Santos', 'rodrigo.santos@email.com', 'senha123', 'Rua Helvétia, 4444', 'Santa Efigênia', 48),
('Isabelly Silva', 'isabelly.silva@email.com', 'senha123', 'Avenida Duque de Caxias, 4545', 'Santa Efigênia', 48),
('Benjamin Oliveira', 'benjamin.oliveira@email.com', 'senha123', 'Largo Coração de Jesus, 4646', 'Santa Efigênia', 48),
('Clarice Souza', 'clarice.souza@email.com', 'senha123', 'Alameda Glete, 4747', 'Santa Efigênia', 48),
('Sebastião Costa', 'sebastiao.costa@email.com', 'senha123', 'Rua das Palmeiras, 4848', 'Santa Cecília', 48),
('Lavínia Pereira', 'lavinia.pereira@email.com', 'senha123', 'Rua Martim Francisco, 4949', 'Santa Cecília', 48);



